# Generated by Django 5.2 on 2025-04-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home_ups', 'Home Ups'), ('solar_power', 'Solar Power'), ('batteries', 'Batteries'), ('ev_charger', 'EV Charger'), ('water_purifier', 'Water Purifier')], max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('sku', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('feature1', models.CharField(max_length=100)),
                ('feature2', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_app.mainpreview')),
            ],
        ),
    ]
