# Generated by Django 5.2 on 2025-06-04 08:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('installation', 'Product Installation'), ('complaint', 'Complaint Registration'), ('service', 'General Service Request'), ('amc', 'AMC Request'), ('business', 'Business Enquiry')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MainPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home_inverter_and_ups', 'Home Inverter/Ups'), ('lithium_inverter_and_ups', 'Lithium Inverter/Ups'), ('solar_power', 'Solar Power'), ('batteries', 'Batteries'), ('li_ion_batteries', 'Lithium Ion Batteries'), ('ev_charger', 'EV Charger'), ('water_purifier', 'Water Purifier')], max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(choices=[('online_inverter_and_ups', 'Online Inverter/Ups'), ('offline_inverter_and_ups', 'Offline Inverter/Ups'), ('hkva_ups', 'HKVA Ups'), ('solar_ups', 'Solar Ups'), ('solar_panel', 'Solar Panel'), ('lithium_solar_inverter', 'Lithium Solar Inverter'), ('MPPTS', 'MPPTS'), ('tubular_batteries', 'Tubular Batteries'), ('solar_batteries', 'Solar Batteries'), ('lithium_ion_batteries', 'Lithium Ion Batteries')], max_length=100)),
                ('variant_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('feature1', models.CharField(max_length=100)),
                ('feature2', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_app.mainpreview')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(choices=[('online_inverter_and_ups', 'Online Inverter/Ups'), ('offline_inverter_and_ups', 'Offline Inverter/Ups'), ('hkva_ups', 'HKVA Ups'), ('solar_ups', 'Solar Ups'), ('solar_panel', 'Solar Panel'), ('lithium_solar_inverter', 'Lithium Solar Inverter'), ('MPPTS', 'MPPTS'), ('tubular_batteries', 'Tubular Batteries'), ('solar_batteries', 'Solar Batteries'), ('lithium_ion_batteries', 'Lithium Ion Batteries')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(blank=True, default=0, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, default=0, null=True, upload_to='images/')),
                ('model_type', models.CharField(blank=True, choices=[('WR', 'WR'), ('NG', 'NG')], max_length=10, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('weight', models.FloatField(default=0)),
                ('voltage', models.FloatField(default=0)),
                ('dimensions', models.CharField(default=0, max_length=100)),
                ('features', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('technical_spec', models.TextField(blank=True, null=True)),
                ('new_arrival', models.BooleanField(default=False)),
                ('va_rating', models.FloatField(blank=True, default=0, null=True)),
                ('warranty', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('product_series', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('wattage', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('suitable_for', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('technology', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('panel_capacity', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('Ah_rating', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_app.mainpreview')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_by_variant', to='warrior_app.previewdetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warrior_app.buynow')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_app.products')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='warrior_app.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warrior_app.products')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='warrior_app.CartItem', to='warrior_app.products'),
        ),
    ]
