# Generated by Django 5.2 on 2025-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewdetails',
            name='feature2',
            field=models.TextField(),
        ),
    ]
