# Generated by Django 5.2 on 2025-05-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0002_alter_previewdetails_feature2'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewdetails',
            name='slogan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
