# Generated by Django 5.2 on 2025-06-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0003_alter_previewdetails_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewdetails',
            name='subcategory',
            field=models.CharField(choices=[('online_inverter_and_ups', 'Online Inverter/Ups'), ('offline_inverter_and_ups', 'Offline Inverter/Ups'), ('hkva_ups', 'HKVA Ups'), ('avr_ups', 'AVR Ups'), ('solar_ups', 'Solar Ups'), ('solar_panel', 'Solar Panel'), ('lithium_solar_inverter', 'Lithium Solar Inverter'), ('MPPTS', 'MPPTS'), ('tubular_batteries', 'Tubular Batteries'), ('solar_batteries', 'Solar Batteries'), ('lithium_ion_batteries', 'Lithium Ion Batteries'), ('lithium_batteries', 'Lithium Batteries')], max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.CharField(choices=[('online_inverter_and_ups', 'Online Inverter/Ups'), ('offline_inverter_and_ups', 'Offline Inverter/Ups'), ('hkva_ups', 'HKVA Ups'), ('avr_ups', 'AVR Ups'), ('solar_ups', 'Solar Ups'), ('solar_panel', 'Solar Panel'), ('lithium_solar_inverter', 'Lithium Solar Inverter'), ('MPPTS', 'MPPTS'), ('tubular_batteries', 'Tubular Batteries'), ('solar_batteries', 'Solar Batteries'), ('lithium_ion_batteries', 'Lithium Ion Batteries'), ('lithium_batteries', 'Lithium Batteries')], max_length=100),
        ),
    ]
