# Generated by Django 5.2 on 2025-06-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0004_alter_previewdetails_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='ordered', max_length=20),
        ),
    ]
