# Generated by Django 5.2 on 2025-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0005_buynow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='est_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
