# Generated by Django 5.2 on 2025-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0005_herocarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='additional_info',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='dimentions',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='features',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='technical_spec',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='voltage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
