# Generated by Django 5.2 on 2025-05-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0006_products_additional_info_products_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='dimentions',
            new_name='dimensions',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
