# Generated by Django 5.2 on 2025-05-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0007_rename_dimentions_products_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warrior_app.previewdetails'),
        ),
    ]
