# Generated by Django 5.2 on 2025-05-02 11:57

from django.db import migrations
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    PreviewDetails = apps.get_model('warrior_app', 'PreviewDetails')
    existing_slugs = set(
        PreviewDetails.objects.exclude(slug__isnull=True).exclude(slug__exact='').values_list('slug', flat=True)
    )
    
    for obj in PreviewDetails.objects.all():
        if not obj.slug:
            base_slug = slugify(obj.variant_name)
            slug = base_slug
            counter = 1
            while slug in existing_slugs:
                slug = f"{base_slug}-{counter}"
                counter += 1
            obj.slug = slug
            obj.save(update_fields=["slug"])
            existing_slugs.add(slug)

class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0009_previewdetails_slug'),  # Replace with your last actual migration if different
    ]

    operations = [
        migrations.RunPython(generate_unique_slugs),
    ]
