# Generated by Django 5.0 on 2026-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0009_dealer_modelnumberandwarrenty_producttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrentyregistration',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrentyregistration',
            name='warranty_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warrentyregistration',
            name='dealer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warrentyregistration',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warrentyregistration',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='warrentyregistration',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warrentyregistration',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
