# Generated by Django 5.0 on 2026-02-24 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0010_warrentyregistration_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrior_app.districtselection'),
        ),
    ]
