# Generated by Django 5.2 on 2025-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0012_populate_unique_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewdetails',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
