# Generated by Django 5.2 on 2025-05-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0013_alter_previewdetails_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previewdetails',
            name='slug',
        ),
    ]
