# Generated by Django 5.2 on 2025-05-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0014_remove_previewdetails_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewdetails',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
