# Generated by Django 5.2 on 2025-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0015_previewdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewdetails',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
