# Generated by Django 5.2 on 2025-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0016_alter_previewdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewdetails',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previewdetails',
            name='slug',
            field=models.SlugField(blank=True, default='temp', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
