# Generated by Django 5.2 on 2025-05-03 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0017_alter_previewdetails_slogan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_app.mainpreview'),
        ),
        migrations.AlterField(
            model_name='products',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrior_app.previewdetails'),
        ),
    ]
