# Generated by Django 5.2 on 2025-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0018_alter_products_category_alter_products_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('installation', 'Product Installation'), ('complaint', 'Complaint Registration'), ('service', 'General Service Request'), ('amc', 'AMC Request'), ('business', 'Business Enquiry')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
