# Generated by Django 5.2 on 2025-05-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0024_products_new_arrival_products_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='images/'),
        ),
    ]
