# Generated by Django 5.2 on 2025-05-13 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0026_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='BuyNow',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='warrior_app.user'),
        ),
    ]
