# Generated by Django 5.2 on 2025-05-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0027_rename_order_buynow_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sku',
        ),
        migrations.AddField(
            model_name='products',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='model_type',
            field=models.CharField(blank=True, choices=[('BR', 'BR'), ('NG', 'NG')], max_length=10, null=True),
        ),
    ]
