# Generated by Django 5.2 on 2025-05-13 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0028_remove_products_sku_products_model_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewdetails',
            name='subcategory',
            field=models.CharField(choices=[('online_ups', 'Online Ups'), ('offline_ups', 'Offline Ups'), ('hkva_ups', 'HKVA Ups'), ('solar_ups', 'Solar Ups'), ('solar_panel', 'Solar Panel'), ('lithium_solar_inverter', 'Lithium Solar Inverter'), ('MPPTS', 'MPPTS'), ('tubular_batteries', 'Tubular Batteries'), ('solar_batteries', 'Solar Batteries'), ('lithium_ion_batteries', 'Lithium Ion Batteries')], default='online_ups', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_by_category', to='warrior_app.previewdetails'),
        ),
        migrations.AlterField(
            model_name='products',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_by_variant', to='warrior_app.previewdetails'),
        ),
    ]
