# Generated by Django 5.2 on 2025-05-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0030_products_type_products_panel_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Ah_rating',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
