# Generated by Django 5.2 on 2025-05-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0032_rename_type_products_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(through='warrior_app.CartItem', to='warrior_app.products'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='warrior_app.user'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
