# Generated by Django 5.2 on 2025-05-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0033_cart_item_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
