# Generated by Django 5.2 on 2025-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0036_alter_mainpreview_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.CharField(choices=[('online_ups', 'Online Ups'), ('offline_ups', 'Offline Ups'), ('hkva_ups', 'HKVA Ups'), ('solar_ups', 'Solar Ups'), ('solar_panel', 'Solar Panel'), ('lithium_solar_inverter', 'Lithium Solar Inverter'), ('MPPTS', 'MPPTS'), ('tubular_batteries', 'Tubular Batteries'), ('solar_batteries', 'Solar Batteries'), ('lithium_ion_batteries', 'Lithium Ion Batteries')], max_length=100),
        ),
    ]
