# Generated by Django 5.2 on 2025-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0037_alter_products_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='model_type',
            field=models.CharField(blank=True, choices=[('WR', 'WR'), ('NG', 'NG')], max_length=10, null=True),
        ),
    ]
