# Generated by Django 5.2 on 2025-05-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0038_alter_products_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warrior_app.products'),
        ),
    ]
