# Generated by Django 5.2 on 2025-05-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0039_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpreview',
            name='category',
            field=models.CharField(choices=[('home_inverter_and_ups', 'Home Inverter/Ups'), ('lithium_inverter_and_ups', 'Lithium Inverter/Ups'), ('solar_power', 'Solar Power'), ('batteries', 'Batteries'), ('li_ion_batteries', 'Lithium Ion Batteries'), ('ev_charger', 'EV Charger'), ('water_purifier', 'Water Purifier')], max_length=100),
        ),
        migrations.AlterField(
            model_name='previewdetails',
            name='subcategory',
            field=models.CharField(choices=[('online_inverter_and_ups', 'Online Inverter/Ups'), ('offline_inverter_and_ups', 'Offline Inverter/Ups'), ('hkva_ups', 'HKVA Ups'), ('solar_ups', 'Solar Ups'), ('solar_panel', 'Solar Panel'), ('lithium_solar_inverter', 'Lithium Solar Inverter'), ('MPPTS', 'MPPTS'), ('tubular_batteries', 'Tubular Batteries'), ('solar_batteries', 'Solar Batteries'), ('lithium_ion_batteries', 'Lithium Ion Batteries')], max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.CharField(choices=[('online_inverter_and_ups', 'Online Inverter/Ups'), ('offline_inverter_and_ups', 'Offline Inverter/Ups'), ('hkva_ups', 'HKVA Ups'), ('solar_ups', 'Solar Ups'), ('solar_panel', 'Solar Panel'), ('lithium_solar_inverter', 'Lithium Solar Inverter'), ('MPPTS', 'MPPTS'), ('tubular_batteries', 'Tubular Batteries'), ('solar_batteries', 'Solar Batteries'), ('lithium_ion_batteries', 'Lithium Ion Batteries')], max_length=100),
        ),
    ]
