# Generated by Django 5.2 on 2025-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0040_alter_mainpreview_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='technical_spec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
