# Generated by Django 5.2 on 2025-05-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrior_app', '0041_alter_products_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewdetails',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
    ]
